spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/libreria
    username: root
    password: 1234
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8082
  #port: 8080
